mkdir app
mkdir app/sass
mkdir app/coffee
mkdir app/src
mkdir app/src/images
mkdir app/src/js
mkdir app/src/css
mkdir assets
mkdir assets/css
mkdir assets/js
mkdir assets/fonts
mkdir layouts
mkdir content
mkdir pages
mkdir partials
bower update
npm install